### ISSUE TITLE
How to use finder-generator in Play Framework SBT project?

### ISSUE THREAD

**Issue by eyeezzi** [ebean-orm-tools/finder-generator#15]
I've also asked this question on [SO](https://stackoverflow.com/q/47172868/4268921). How would I configure my SBT project so the `finder-generator` can generate _query beans_ for the _entity beans_ in my SBT project? From reading the [Ebean documentation](), the only thing I could do was to add the following line to my `build.sbt` file

    libraryDependencies += "io.ebean.tools" % "finder-generator" % "${version}"

Then I need to configure the generator to tell it where to find the compiled .class files of my entity beans etc __but I don't know how to do this in an SBT project__

Any help will be appreciated.

**Comment by rbygrave** [comment]
Hi, Ah sorry ... missed this question.  Note that the best place for questions is the google forum - https://groups.google.com/forum/#!forum/ebean ... as many more people will see it and it is much less likely to get forgotten about.

Anyhow, your question ... 

> how to do this in an SBT project

Yes, I don't know that. Right now ... we run the finder-generator as an interactive maven plugin.  I'll look to also add a Gradle plugin in the reasonably near future.  Ideally we would have an SBT plugin as well but I don't know what is involved.  

You could try posting this on the Ebean google group forum.  There are Play / SBT people that could help move this forward.

Cheers, Rob.

**Comment by rbygrave** [comment]
So now we have the command line tool - http://ebean-orm.github.io/docs/getting-started/cli-tool

And I'd recommend you try that out.  That generates finders and query beans.  I'll close this now.
