### ISSUE TITLE
kotlin generator bug

### ISSUE THREAD

**Issue by BrettCao** [ebean-orm-tools/finder-generator#26]
Lack of body 
open class UserFinder : Finder<Long, User>(User::class.java) {
}
....

**Comment by rbygrave** [comment]
What is the problem with that?
Refactor adding a function ... will add the body braces etc.

**Comment by BrettCao** [comment]
Missing body braces now

**Comment by rbygrave** [comment]
Yes that is correct and intended.  

So what is the problem?  Are you unable to compile or something?

**Comment by BrettCao** [comment]
Yes,If missing {}:
Error:(14, 30) Kotlin: Unresolved reference: db

**Comment by BrettCao** [comment]
Unable to compile

**Comment by rbygrave** [comment]
This doesn't really make sense to me.  Show me all the code for the file/class that is unable to compile.  Does it not contain a method that you added?  When you added it you didn't add the brackets for the body for some reason?

**Comment by BrettCao** [comment]
Missing “{}” when auto-generated Finder, now need to be manually added to compile

**Comment by BrettCao** [comment]
@Override
  public void finderClass(FileWriter writer, String shortName, String idTypeShortName) throws IOException {

    //open class AddressFinder : Finder<Long, Address>(Address::class.java)

    writer.append("open class ").append("").append(shortName).append("Finder")
      .append(" : Finder<").append(idTypeShortName).append(", ")
      .append(shortName).append(">(").append(shortName).append("::class.java)")
      .append(NEWLINE);
  }

to

  @Override
  public void finderClass(FileWriter writer, String shortName, String idTypeShortName) throws IOException {

    //open class AddressFinder : Finder<Long, Address>(Address::class.java)

    writer.append("open class ").append("").append(shortName).append("Finder")
      .append(" : Finder<").append(idTypeShortName).append(", ")
      .append(shortName).append(">(").append(shortName).append("::class.java){")
      .append(NEWLINE);
  }

  @Override
  public void finderClassEnd(FileWriter writer) throws IOException {
    writer.append("}").append(NEWLINE);
  }

**Comment by rbygrave** [comment]
Yeah, I still don't understand.

I think you are saying 
```kotlin
open class AddressFinder : Finder<Long, Address>(Address::class.java)
```
The above does not compile.  For me it does compile, it is valid Kotlin.

**Comment by rbygrave** [comment]
I think this issue is likely to be the same as https://github.com/ebean-orm-tools/finder-generator/pull/30

So I guess we can close this.
