### ISSUE TITLE
GeneratorConfig.setLang only for Kotlin

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm-tools/finder-generator#27]
In method `GeneratorConfig.setLang`:
```java
  public void setLang(String lang) {
    this.lang = lang;
    this.languageAdapter = new KotlinLangAdapter();
  }
```
is something wrong, because if I set "java" then `KotlinLangAdapter` is assigned.

I think that there should be something like `isJava`/`isKotlin` - that is `enableJava`/`enableKotlin`.

**Comment by rbygrave** [comment]
Well, the way finder-generator is used is via ebeaninit - https://github.com/ebean-orm-tools/ebean-init

When generating Java code it doesn't call setLang() ... it only calls setLang() when it is generating Kotlin code.
Refer: https://github.com/ebean-orm-tools/ebean-init/blob/master/src/main/java/io/ebean/tools/init/action/DoGenerate.java#L92

So yes we could fix up setLang() to also support Java ... but not sure why you are not using ebeaninit?  https://ebean.io/docs/getting-started/cli-tool

ebeaninit can do more now, full setup of a maven or gradle project basically.  Plus ebeaninit is going to be where we do some more cool stuff like suggest code changes for queries based on profiling.

But yes, this should be fixed ...

**Comment by Ryszard-Trojnacki** [comment]
I don't need this function. I just spotted that it is wrong, while searching for https://github.com/ebean-orm-tools/finder-generator/issues/28.

**Comment by rbygrave** [comment]
Fixed by https://github.com/ebean-orm-tools/finder-generator/pull/29
